#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 81
#define LARGE_STATE_COUNT 33
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  sym_number = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DASH = 5,
  anon_sym_STAR = 6,
  anon_sym_SLASH = 7,
  anon_sym_PLUS = 8,
  anon_sym_ifz = 9,
  anon_sym_fn = 10,
  anon_sym_EQ_GT = 11,
  anon_sym_let = 12,
  anon_sym_EQ = 13,
  anon_sym_in = 14,
  sym_source_file = 15,
  sym__arg = 16,
  sym_parens_expr = 17,
  sym__expr = 18,
  sym_unary_expr = 19,
  sym_binary_expr = 20,
  sym_ifz_expr = 21,
  sym_app_expr = 22,
  sym_fn_expr = 23,
  sym_let_expr = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_app_expr_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_ifz] = "ifz",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_in] = "in",
  [sym_source_file] = "source_file",
  [sym__arg] = "_arg",
  [sym_parens_expr] = "parens_expr",
  [sym__expr] = "_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_ifz_expr] = "ifz_expr",
  [sym_app_expr] = "app_expr",
  [sym_fn_expr] = "fn_expr",
  [sym_let_expr] = "let_expr",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_app_expr_repeat1] = "app_expr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_ifz] = anon_sym_ifz,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_in] = anon_sym_in,
  [sym_source_file] = sym_source_file,
  [sym__arg] = sym__arg,
  [sym_parens_expr] = sym_parens_expr,
  [sym__expr] = sym__expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_ifz_expr] = sym_ifz_expr,
  [sym_app_expr] = sym_app_expr,
  [sym_fn_expr] = sym_fn_expr,
  [sym_let_expr] = sym_let_expr,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_app_expr_repeat1] = aux_sym_app_expr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ifz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__arg] = {
    .visible = false,
    .named = true,
  },
  [sym_parens_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_ifz_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_app_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_let_expr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_app_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 7,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 9,
  [15] = 9,
  [16] = 13,
  [17] = 17,
  [18] = 6,
  [19] = 17,
  [20] = 7,
  [21] = 11,
  [22] = 4,
  [23] = 17,
  [24] = 13,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 28,
  [34] = 29,
  [35] = 31,
  [36] = 32,
  [37] = 37,
  [38] = 38,
  [39] = 26,
  [40] = 37,
  [41] = 29,
  [42] = 38,
  [43] = 27,
  [44] = 44,
  [45] = 30,
  [46] = 37,
  [47] = 31,
  [48] = 48,
  [49] = 30,
  [50] = 32,
  [51] = 27,
  [52] = 38,
  [53] = 28,
  [54] = 26,
  [55] = 48,
  [56] = 44,
  [57] = 48,
  [58] = 44,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 59,
  [63] = 60,
  [64] = 61,
  [65] = 61,
  [66] = 60,
  [67] = 59,
  [68] = 68,
  [69] = 68,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 68,
  [75] = 71,
  [76] = 71,
  [77] = 70,
  [78] = 70,
  [79] = 73,
  [80] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == 'f') ADVANCE(9);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(16);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == 'i') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(9);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'z') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_ifz);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_ifz] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(72),
    [sym__arg] = STATE(25),
    [sym_parens_expr] = STATE(25),
    [sym__expr] = STATE(25),
    [sym_unary_expr] = STATE(25),
    [sym_binary_expr] = STATE(25),
    [sym_ifz_expr] = STATE(25),
    [sym_app_expr] = STATE(25),
    [sym_fn_expr] = STATE(25),
    [sym_let_expr] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [2] = {
    [sym__arg] = STATE(25),
    [sym_parens_expr] = STATE(25),
    [sym__expr] = STATE(25),
    [sym_unary_expr] = STATE(25),
    [sym_binary_expr] = STATE(25),
    [sym_ifz_expr] = STATE(25),
    [sym_app_expr] = STATE(25),
    [sym_fn_expr] = STATE(25),
    [sym_let_expr] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_identifier] = ACTIONS(5),
    [sym_number] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [3] = {
    [sym__arg] = STATE(25),
    [sym_parens_expr] = STATE(25),
    [sym__expr] = STATE(25),
    [sym_unary_expr] = STATE(25),
    [sym_binary_expr] = STATE(25),
    [sym_ifz_expr] = STATE(25),
    [sym_app_expr] = STATE(25),
    [sym_fn_expr] = STATE(25),
    [sym_let_expr] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [sym_number] = ACTIONS(26),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(32),
    [anon_sym_ifz] = ACTIONS(35),
    [anon_sym_fn] = ACTIONS(38),
    [anon_sym_let] = ACTIONS(41),
  },
  [4] = {
    [sym__arg] = STATE(42),
    [sym_parens_expr] = STATE(42),
    [sym__expr] = STATE(42),
    [sym_unary_expr] = STATE(42),
    [sym_binary_expr] = STATE(42),
    [sym_ifz_expr] = STATE(42),
    [sym_app_expr] = STATE(42),
    [sym_fn_expr] = STATE(42),
    [sym_let_expr] = STATE(42),
    [sym_identifier] = ACTIONS(44),
    [sym_number] = ACTIONS(46),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [5] = {
    [sym__arg] = STATE(38),
    [sym_parens_expr] = STATE(38),
    [sym__expr] = STATE(38),
    [sym_unary_expr] = STATE(38),
    [sym_binary_expr] = STATE(38),
    [sym_ifz_expr] = STATE(38),
    [sym_app_expr] = STATE(38),
    [sym_fn_expr] = STATE(38),
    [sym_let_expr] = STATE(38),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [6] = {
    [sym__arg] = STATE(40),
    [sym_parens_expr] = STATE(40),
    [sym__expr] = STATE(40),
    [sym_unary_expr] = STATE(40),
    [sym_binary_expr] = STATE(40),
    [sym_ifz_expr] = STATE(40),
    [sym_app_expr] = STATE(40),
    [sym_fn_expr] = STATE(40),
    [sym_let_expr] = STATE(40),
    [sym_identifier] = ACTIONS(62),
    [sym_number] = ACTIONS(64),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [7] = {
    [sym__arg] = STATE(30),
    [sym_parens_expr] = STATE(30),
    [sym__expr] = STATE(30),
    [sym_unary_expr] = STATE(30),
    [sym_binary_expr] = STATE(30),
    [sym_ifz_expr] = STATE(30),
    [sym_app_expr] = STATE(30),
    [sym_fn_expr] = STATE(30),
    [sym_let_expr] = STATE(30),
    [sym_identifier] = ACTIONS(76),
    [sym_number] = ACTIONS(78),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [8] = {
    [sym__arg] = STATE(46),
    [sym_parens_expr] = STATE(46),
    [sym__expr] = STATE(46),
    [sym_unary_expr] = STATE(46),
    [sym_binary_expr] = STATE(46),
    [sym_ifz_expr] = STATE(46),
    [sym_app_expr] = STATE(46),
    [sym_fn_expr] = STATE(46),
    [sym_let_expr] = STATE(46),
    [sym_identifier] = ACTIONS(80),
    [sym_number] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [9] = {
    [sym__arg] = STATE(39),
    [sym_parens_expr] = STATE(39),
    [sym__expr] = STATE(39),
    [sym_unary_expr] = STATE(39),
    [sym_binary_expr] = STATE(39),
    [sym_ifz_expr] = STATE(39),
    [sym_app_expr] = STATE(39),
    [sym_fn_expr] = STATE(39),
    [sym_let_expr] = STATE(39),
    [sym_identifier] = ACTIONS(84),
    [sym_number] = ACTIONS(86),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [10] = {
    [sym__arg] = STATE(49),
    [sym_parens_expr] = STATE(49),
    [sym__expr] = STATE(49),
    [sym_unary_expr] = STATE(49),
    [sym_binary_expr] = STATE(49),
    [sym_ifz_expr] = STATE(49),
    [sym_app_expr] = STATE(49),
    [sym_fn_expr] = STATE(49),
    [sym_let_expr] = STATE(49),
    [sym_identifier] = ACTIONS(88),
    [sym_number] = ACTIONS(90),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [11] = {
    [sym__arg] = STATE(43),
    [sym_parens_expr] = STATE(43),
    [sym__expr] = STATE(43),
    [sym_unary_expr] = STATE(43),
    [sym_binary_expr] = STATE(43),
    [sym_ifz_expr] = STATE(43),
    [sym_app_expr] = STATE(43),
    [sym_fn_expr] = STATE(43),
    [sym_let_expr] = STATE(43),
    [sym_identifier] = ACTIONS(92),
    [sym_number] = ACTIONS(94),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [12] = {
    [sym__arg] = STATE(51),
    [sym_parens_expr] = STATE(51),
    [sym__expr] = STATE(51),
    [sym_unary_expr] = STATE(51),
    [sym_binary_expr] = STATE(51),
    [sym_ifz_expr] = STATE(51),
    [sym_app_expr] = STATE(51),
    [sym_fn_expr] = STATE(51),
    [sym_let_expr] = STATE(51),
    [sym_identifier] = ACTIONS(96),
    [sym_number] = ACTIONS(98),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [13] = {
    [sym__arg] = STATE(53),
    [sym_parens_expr] = STATE(53),
    [sym__expr] = STATE(53),
    [sym_unary_expr] = STATE(53),
    [sym_binary_expr] = STATE(53),
    [sym_ifz_expr] = STATE(53),
    [sym_app_expr] = STATE(53),
    [sym_fn_expr] = STATE(53),
    [sym_let_expr] = STATE(53),
    [sym_identifier] = ACTIONS(100),
    [sym_number] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [14] = {
    [sym__arg] = STATE(54),
    [sym_parens_expr] = STATE(54),
    [sym__expr] = STATE(54),
    [sym_unary_expr] = STATE(54),
    [sym_binary_expr] = STATE(54),
    [sym_ifz_expr] = STATE(54),
    [sym_app_expr] = STATE(54),
    [sym_fn_expr] = STATE(54),
    [sym_let_expr] = STATE(54),
    [sym_identifier] = ACTIONS(104),
    [sym_number] = ACTIONS(106),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [15] = {
    [sym__arg] = STATE(26),
    [sym_parens_expr] = STATE(26),
    [sym__expr] = STATE(26),
    [sym_unary_expr] = STATE(26),
    [sym_binary_expr] = STATE(26),
    [sym_ifz_expr] = STATE(26),
    [sym_app_expr] = STATE(26),
    [sym_fn_expr] = STATE(26),
    [sym_let_expr] = STATE(26),
    [sym_identifier] = ACTIONS(108),
    [sym_number] = ACTIONS(110),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [16] = {
    [sym__arg] = STATE(28),
    [sym_parens_expr] = STATE(28),
    [sym__expr] = STATE(28),
    [sym_unary_expr] = STATE(28),
    [sym_binary_expr] = STATE(28),
    [sym_ifz_expr] = STATE(28),
    [sym_app_expr] = STATE(28),
    [sym_fn_expr] = STATE(28),
    [sym_let_expr] = STATE(28),
    [sym_identifier] = ACTIONS(112),
    [sym_number] = ACTIONS(114),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [17] = {
    [sym__arg] = STATE(35),
    [sym_parens_expr] = STATE(35),
    [sym__expr] = STATE(35),
    [sym_unary_expr] = STATE(35),
    [sym_binary_expr] = STATE(35),
    [sym_ifz_expr] = STATE(35),
    [sym_app_expr] = STATE(35),
    [sym_fn_expr] = STATE(35),
    [sym_let_expr] = STATE(35),
    [sym_identifier] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [18] = {
    [sym__arg] = STATE(37),
    [sym_parens_expr] = STATE(37),
    [sym__expr] = STATE(37),
    [sym_unary_expr] = STATE(37),
    [sym_binary_expr] = STATE(37),
    [sym_ifz_expr] = STATE(37),
    [sym_app_expr] = STATE(37),
    [sym_fn_expr] = STATE(37),
    [sym_let_expr] = STATE(37),
    [sym_identifier] = ACTIONS(120),
    [sym_number] = ACTIONS(122),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [19] = {
    [sym__arg] = STATE(47),
    [sym_parens_expr] = STATE(47),
    [sym__expr] = STATE(47),
    [sym_unary_expr] = STATE(47),
    [sym_binary_expr] = STATE(47),
    [sym_ifz_expr] = STATE(47),
    [sym_app_expr] = STATE(47),
    [sym_fn_expr] = STATE(47),
    [sym_let_expr] = STATE(47),
    [sym_identifier] = ACTIONS(124),
    [sym_number] = ACTIONS(126),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [20] = {
    [sym__arg] = STATE(45),
    [sym_parens_expr] = STATE(45),
    [sym__expr] = STATE(45),
    [sym_unary_expr] = STATE(45),
    [sym_binary_expr] = STATE(45),
    [sym_ifz_expr] = STATE(45),
    [sym_app_expr] = STATE(45),
    [sym_fn_expr] = STATE(45),
    [sym_let_expr] = STATE(45),
    [sym_identifier] = ACTIONS(128),
    [sym_number] = ACTIONS(130),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [21] = {
    [sym__arg] = STATE(27),
    [sym_parens_expr] = STATE(27),
    [sym__expr] = STATE(27),
    [sym_unary_expr] = STATE(27),
    [sym_binary_expr] = STATE(27),
    [sym_ifz_expr] = STATE(27),
    [sym_app_expr] = STATE(27),
    [sym_fn_expr] = STATE(27),
    [sym_let_expr] = STATE(27),
    [sym_identifier] = ACTIONS(132),
    [sym_number] = ACTIONS(134),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [22] = {
    [sym__arg] = STATE(52),
    [sym_parens_expr] = STATE(52),
    [sym__expr] = STATE(52),
    [sym_unary_expr] = STATE(52),
    [sym_binary_expr] = STATE(52),
    [sym_ifz_expr] = STATE(52),
    [sym_app_expr] = STATE(52),
    [sym_fn_expr] = STATE(52),
    [sym_let_expr] = STATE(52),
    [sym_identifier] = ACTIONS(136),
    [sym_number] = ACTIONS(138),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(50),
    [anon_sym_ifz] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(56),
  },
  [23] = {
    [sym__arg] = STATE(31),
    [sym_parens_expr] = STATE(31),
    [sym__expr] = STATE(31),
    [sym_unary_expr] = STATE(31),
    [sym_binary_expr] = STATE(31),
    [sym_ifz_expr] = STATE(31),
    [sym_app_expr] = STATE(31),
    [sym_fn_expr] = STATE(31),
    [sym_let_expr] = STATE(31),
    [sym_identifier] = ACTIONS(140),
    [sym_number] = ACTIONS(142),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_ifz] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(17),
  },
  [24] = {
    [sym__arg] = STATE(33),
    [sym_parens_expr] = STATE(33),
    [sym__expr] = STATE(33),
    [sym_unary_expr] = STATE(33),
    [sym_binary_expr] = STATE(33),
    [sym_ifz_expr] = STATE(33),
    [sym_app_expr] = STATE(33),
    [sym_fn_expr] = STATE(33),
    [sym_let_expr] = STATE(33),
    [sym_identifier] = ACTIONS(144),
    [sym_number] = ACTIONS(146),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(68),
    [anon_sym_ifz] = ACTIONS(70),
    [anon_sym_fn] = ACTIONS(72),
    [anon_sym_let] = ACTIONS(74),
  },
  [25] = {
    [sym__arg] = STATE(32),
    [sym_parens_expr] = STATE(32),
    [aux_sym_app_expr_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(148),
    [sym_identifier] = ACTIONS(150),
    [sym_number] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(154),
    [anon_sym_STAR] = ACTIONS(156),
    [anon_sym_SLASH] = ACTIONS(156),
    [anon_sym_PLUS] = ACTIONS(154),
    [anon_sym_ifz] = ACTIONS(158),
    [anon_sym_fn] = ACTIONS(158),
    [anon_sym_let] = ACTIONS(158),
  },
  [26] = {
    [sym__arg] = STATE(32),
    [sym_parens_expr] = STATE(32),
    [aux_sym_app_expr_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(160),
    [sym_identifier] = ACTIONS(150),
    [sym_number] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(160),
    [anon_sym_STAR] = ACTIONS(156),
    [anon_sym_SLASH] = ACTIONS(156),
    [anon_sym_PLUS] = ACTIONS(160),
    [anon_sym_ifz] = ACTIONS(162),
    [anon_sym_fn] = ACTIONS(162),
    [anon_sym_let] = ACTIONS(162),
  },
  [27] = {
    [sym__arg] = STATE(32),
    [sym_parens_expr] = STATE(32),
    [aux_sym_app_expr_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(164),
    [sym_identifier] = ACTIONS(150),
    [sym_number] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(154),
    [anon_sym_STAR] = ACTIONS(156),
    [anon_sym_SLASH] = ACTIONS(156),
    [anon_sym_PLUS] = ACTIONS(154),
    [anon_sym_ifz] = ACTIONS(166),
    [anon_sym_fn] = ACTIONS(166),
    [anon_sym_let] = ACTIONS(166),
  },
  [28] = {
    [sym__arg] = STATE(32),
    [sym_parens_expr] = STATE(32),
    [aux_sym_app_expr_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(160),
    [sym_identifier] = ACTIONS(150),
    [sym_number] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(160),
    [anon_sym_STAR] = ACTIONS(160),
    [anon_sym_SLASH] = ACTIONS(160),
    [anon_sym_PLUS] = ACTIONS(160),
    [anon_sym_ifz] = ACTIONS(162),
    [anon_sym_fn] = ACTIONS(162),
    [anon_sym_let] = ACTIONS(162),
  },
  [29] = {
    [sym__arg] = STATE(29),
    [sym_parens_expr] = STATE(29),
    [aux_sym_app_expr_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(168),
    [sym_identifier] = ACTIONS(170),
    [sym_number] = ACTIONS(173),
    [anon_sym_LPAREN] = ACTIONS(176),
    [anon_sym_DASH] = ACTIONS(168),
    [anon_sym_STAR] = ACTIONS(168),
    [anon_sym_SLASH] = ACTIONS(168),
    [anon_sym_PLUS] = ACTIONS(168),
    [anon_sym_ifz] = ACTIONS(179),
    [anon_sym_fn] = ACTIONS(179),
    [anon_sym_let] = ACTIONS(179),
  },
  [30] = {
    [sym__arg] = STATE(32),
    [sym_parens_expr] = STATE(32),
    [aux_sym_app_expr_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(181),
    [sym_identifier] = ACTIONS(150),
    [sym_number] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(154),
    [anon_sym_STAR] = ACTIONS(156),
    [anon_sym_SLASH] = ACTIONS(156),
    [anon_sym_PLUS] = ACTIONS(154),
    [anon_sym_ifz] = ACTIONS(183),
    [anon_sym_fn] = ACTIONS(183),
    [anon_sym_let] = ACTIONS(183),
  },
  [31] = {
    [sym__arg] = STATE(32),
    [sym_parens_expr] = STATE(32),
    [aux_sym_app_expr_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(185),
    [sym_identifier] = ACTIONS(150),
    [sym_number] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(185),
    [anon_sym_STAR] = ACTIONS(185),
    [anon_sym_SLASH] = ACTIONS(185),
    [anon_sym_PLUS] = ACTIONS(185),
    [anon_sym_ifz] = ACTIONS(187),
    [anon_sym_fn] = ACTIONS(187),
    [anon_sym_let] = ACTIONS(187),
  },
  [32] = {
    [sym__arg] = STATE(29),
    [sym_parens_expr] = STATE(29),
    [aux_sym_app_expr_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(189),
    [sym_identifier] = ACTIONS(191),
    [sym_number] = ACTIONS(189),
    [anon_sym_LPAREN] = ACTIONS(189),
    [anon_sym_DASH] = ACTIONS(189),
    [anon_sym_STAR] = ACTIONS(189),
    [anon_sym_SLASH] = ACTIONS(189),
    [anon_sym_PLUS] = ACTIONS(189),
    [anon_sym_ifz] = ACTIONS(191),
    [anon_sym_fn] = ACTIONS(191),
    [anon_sym_let] = ACTIONS(191),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(160), 5,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [20] = 6,
    ACTIONS(179), 1,
      anon_sym_in,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(198), 1,
      sym_number,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
    STATE(34), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(168), 4,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [44] = 4,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(185), 5,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [64] = 2,
    STATE(41), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(189), 8,
      sym_identifier,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [80] = 6,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    ACTIONS(206), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(208), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [104] = 7,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    ACTIONS(218), 1,
      anon_sym_in,
    ACTIONS(214), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(216), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [130] = 5,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    ACTIONS(208), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 3,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [152] = 6,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    ACTIONS(206), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(208), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [176] = 4,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    ACTIONS(222), 2,
      sym_identifier,
      sym_number,
    STATE(41), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(168), 5,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [196] = 7,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    ACTIONS(228), 1,
      anon_sym_in,
    ACTIONS(214), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(216), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [222] = 6,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    ACTIONS(206), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(208), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [246] = 2,
    ACTIONS(232), 4,
      sym_identifier,
      anon_sym_ifz,
      anon_sym_fn,
      anon_sym_let,
    ACTIONS(230), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [262] = 6,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    ACTIONS(206), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(208), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [286] = 6,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 2,
      sym_identifier,
      sym_number,
    ACTIONS(206), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(208), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(36), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [310] = 6,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      anon_sym_in,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(185), 4,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [334] = 2,
    ACTIONS(238), 4,
      sym_identifier,
      anon_sym_ifz,
      anon_sym_fn,
      anon_sym_let,
    ACTIONS(236), 7,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [350] = 7,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 1,
      anon_sym_in,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    ACTIONS(214), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(216), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [376] = 3,
    ACTIONS(191), 2,
      sym_identifier,
      anon_sym_in,
    STATE(34), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(189), 6,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [394] = 7,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 1,
      anon_sym_in,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    ACTIONS(214), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(216), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [420] = 7,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    ACTIONS(240), 1,
      anon_sym_in,
    ACTIONS(214), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(216), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [446] = 6,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      anon_sym_in,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
    ACTIONS(160), 4,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [470] = 7,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      anon_sym_in,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(216), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(50), 3,
      sym__arg,
      sym_parens_expr,
      aux_sym_app_expr_repeat1,
  [496] = 1,
    ACTIONS(236), 8,
      sym_identifier,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [507] = 2,
    ACTIONS(232), 2,
      sym_identifier,
      anon_sym_in,
    ACTIONS(230), 6,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [520] = 2,
    ACTIONS(238), 2,
      sym_identifier,
      anon_sym_in,
    ACTIONS(236), 6,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [533] = 1,
    ACTIONS(230), 8,
      sym_identifier,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [544] = 3,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(242), 2,
      sym_identifier,
      sym_number,
    STATE(56), 2,
      sym__arg,
      sym_parens_expr,
  [556] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(244), 2,
      sym_identifier,
      sym_number,
    STATE(62), 2,
      sym__arg,
      sym_parens_expr,
  [568] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(246), 2,
      sym_identifier,
      sym_number,
    STATE(66), 2,
      sym__arg,
      sym_parens_expr,
  [580] = 3,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(248), 2,
      sym_identifier,
      sym_number,
    STATE(44), 2,
      sym__arg,
      sym_parens_expr,
  [592] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(250), 2,
      sym_identifier,
      sym_number,
    STATE(67), 2,
      sym__arg,
      sym_parens_expr,
  [604] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(252), 2,
      sym_identifier,
      sym_number,
    STATE(63), 2,
      sym__arg,
      sym_parens_expr,
  [616] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(254), 2,
      sym_identifier,
      sym_number,
    STATE(60), 2,
      sym__arg,
      sym_parens_expr,
  [628] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(256), 2,
      sym_identifier,
      sym_number,
    STATE(59), 2,
      sym__arg,
      sym_parens_expr,
  [640] = 3,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(258), 2,
      sym_identifier,
      sym_number,
    STATE(58), 2,
      sym__arg,
      sym_parens_expr,
  [652] = 1,
    ACTIONS(260), 1,
      anon_sym_EQ_GT,
  [656] = 1,
    ACTIONS(262), 1,
      anon_sym_EQ_GT,
  [660] = 1,
    ACTIONS(264), 1,
      anon_sym_EQ,
  [664] = 1,
    ACTIONS(266), 1,
      sym_identifier,
  [668] = 1,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
  [672] = 1,
    ACTIONS(270), 1,
      sym_identifier,
  [676] = 1,
    ACTIONS(272), 1,
      anon_sym_EQ_GT,
  [680] = 1,
    ACTIONS(274), 1,
      sym_identifier,
  [684] = 1,
    ACTIONS(276), 1,
      sym_identifier,
  [688] = 1,
    ACTIONS(278), 1,
      anon_sym_EQ,
  [692] = 1,
    ACTIONS(280), 1,
      anon_sym_EQ,
  [696] = 1,
    ACTIONS(282), 1,
      sym_identifier,
  [700] = 1,
    ACTIONS(284), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(33)] = 0,
  [SMALL_STATE(34)] = 20,
  [SMALL_STATE(35)] = 44,
  [SMALL_STATE(36)] = 64,
  [SMALL_STATE(37)] = 80,
  [SMALL_STATE(38)] = 104,
  [SMALL_STATE(39)] = 130,
  [SMALL_STATE(40)] = 152,
  [SMALL_STATE(41)] = 176,
  [SMALL_STATE(42)] = 196,
  [SMALL_STATE(43)] = 222,
  [SMALL_STATE(44)] = 246,
  [SMALL_STATE(45)] = 262,
  [SMALL_STATE(46)] = 286,
  [SMALL_STATE(47)] = 310,
  [SMALL_STATE(48)] = 334,
  [SMALL_STATE(49)] = 350,
  [SMALL_STATE(50)] = 376,
  [SMALL_STATE(51)] = 394,
  [SMALL_STATE(52)] = 420,
  [SMALL_STATE(53)] = 446,
  [SMALL_STATE(54)] = 470,
  [SMALL_STATE(55)] = 496,
  [SMALL_STATE(56)] = 507,
  [SMALL_STATE(57)] = 520,
  [SMALL_STATE(58)] = 533,
  [SMALL_STATE(59)] = 544,
  [SMALL_STATE(60)] = 556,
  [SMALL_STATE(61)] = 568,
  [SMALL_STATE(62)] = 580,
  [SMALL_STATE(63)] = 592,
  [SMALL_STATE(64)] = 604,
  [SMALL_STATE(65)] = 616,
  [SMALL_STATE(66)] = 628,
  [SMALL_STATE(67)] = 640,
  [SMALL_STATE(68)] = 652,
  [SMALL_STATE(69)] = 656,
  [SMALL_STATE(70)] = 660,
  [SMALL_STATE(71)] = 664,
  [SMALL_STATE(72)] = 668,
  [SMALL_STATE(73)] = 672,
  [SMALL_STATE(74)] = 676,
  [SMALL_STATE(75)] = 680,
  [SMALL_STATE(76)] = 684,
  [SMALL_STATE(77)] = 688,
  [SMALL_STATE(78)] = 692,
  [SMALL_STATE(79)] = 696,
  [SMALL_STATE(80)] = 700,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(65),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_expr, 4),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_expr, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(29),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(29),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(18),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_app_expr_repeat1, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_expr, 6),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_expr, 6),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expr, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_app_expr, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_app_expr, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(34),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(34),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(6),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(41),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_expr_repeat1, 2), SHIFT_REPEAT(8),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ifz_expr, 4),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ifz_expr, 4),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens_expr, 3),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parens_expr, 3),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [268] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lambda(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
